# Static site Cloudflare Workers configuration
name = "nspass-web"
main = "functions/index.js"
compatibility_date = "2024-01-01"

# Rolldown build output configuration
[assets]
directory = "./dist"

# Environment variables
[vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.nspass.xforward.de"
