# 静态站点 Cloudflare Workers 配置
name = "nspass-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Vite构建输出配置
[assets]
directory = "./out"

# 环境变量
[vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.nspass.xforward.de"
