# Cloudflare Pages 配置文件
name = "nspass-web"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 构建配置
[build]
command = "git submodule update --init --recursive --depth 1 || echo 'Submodule update failed, continuing...' && npm run build:cloudflare:safe"
publish = ".vercel/output/static"
