# Cloudflare Pages 配置文件
name = "nspass-web"
compatibility_date = "2024-12-01"

# Pages 配置
[pages_build_output_dir]
# 使用 @cloudflare/next-on-pages 生成的输出目录
output_dir = ".vercel/output/static"

# 环境变量
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"

# 构建配置
[build]
command = "npm run build:cloudflare"
publish = ".vercel/output/static"

# 函数配置（如果需要）
[functions]
# 启用 Node.js 兼容性
nodejs_compat = true
