# Cloudflare Pages 配置文件
name = "nspass-web"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 构建配置
[build]
command = "npm run build:cloudflare"
publish = ".vercel/output/static"

# 环境变量
[env.production]
SKIP_TYPE_CHECK = "true"
