# 静态站点 Cloudflare Workers 配置
name = "nspass-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 静态文件配置 - 自动上传 out 目录到 KV
[site]
bucket = "./out"

# 环境变量
[vars]
NODE_ENV = "production"
API_BASE_URL = "https://api.nspass.xforward.de"
