# Static site Cloudflare Workers configuration
name = "nspass-web"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Static assets configuration
[assets]
directory = "./dist"
binding = "__STATIC_CONTENT"

# Environment variables
[vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.nspass.xforward.de"
VITE_ENABLE_MSW = "false"
