# Cloudflare Pages 配置文件
name = "nspass-web"

# Pages 项目配置 - 仅用于 Pages 部署
pages_build_output_dir = "out"

# 生产环境变量配置
[env.production.vars]
SKIP_TYPE_CHECK = "true"

# 预览环境变量配置
[env.preview.vars]
SKIP_TYPE_CHECK = "true"
