# Cloudflare Workers 配置文件
name = "nspass-web"
main = "src/index.js"
compatibility_date = "2023-10-30"

# 静态资源配置
[site]
bucket = "./out"

# 环境变量配置
[vars]
NODE_ENV = "production"

# 生产环境变量
[env.production]
name = "nspass-web"

[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

# 预览环境变量
[env.staging]
name = "nspass-web-staging"

[env.staging.vars]
NODE_ENV = "production"
ENVIRONMENT = "staging"
